[package]
name = "nata"
version = "0.1.0"
authors = ["Emmanuel Thompson <eet6646@gmail.com>"]
edition = "2018"
rust-version = "1.88"
license = "MIT or Apache-2.0"
repository = "https://github.com/sharksforarms/nata"
keywords = ["packet", "network", "serialization", "deserialization", "parse"]
categories = ["network-programming", "simulation", "parsing", "no-std"]
description = "Network packet manipulation toolkit"
readme = "README.md"

[package.metadata.docs.rs]
features = ["pnet", "libpcap"]

[features]
default = ["std"]
std = ["pnet", "pcap-file"]
libpcap = ["pnet/pcap"]

[dependencies]
hashbrown = "0.17"
deku = { version = "0.20", default-features = false, features = ["alloc", "bits", "descriptive-errors"] }
pnet = { version = "0.35", optional = true }
pcap-file = { version = "2.0", optional = true }

[dev-dependencies]
rstest = "0.26"
hexlit = "0.5.5"
criterion = "0.8"

[[bench]]
name = "bench_layers"
harness = false

[[example]]
name = "read_write_pcap"
required-features = ["std"]

[[example]]
name = "icmp_ping"
required-features = ["std", "libpcap"]

[[example]]
name = "read_write_interface"
required-features = ["std", "libpcap"]

[[example]]
name = "spoof_http_server"
required-features = ["std", "libpcap"]
